name: Update Languages
on:
  schedule:
    - cron: '11 19 * * MON'
  push:
    paths-ignore:
      - 'src/languages.json'
      - 'README.md'
jobs:
  update_colours:
    name: Update Languages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - uses: actions/setup-python@v5
        with:
          python-version: '2.7.18'
          
      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      - name: Update languages
        run: 'python github-languages.py'
      - name: Commit
        run: |
          git config --local user.name "kjxbyz"
          git config --local user.email "kjxbyz888@outlook.com"
          git add -A
          git diff-index --quiet HEAD || git commit -m 'Update languages.json'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
